name: osrm-backend CI
on:
  push:
    branches:
      - master
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
      - v[1-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+
      - v[1-9]+.[0-9]+-[0-9a-zA-Z]+
  pull_request:
    branches:
      - master

env:
  CCACHE_TEMPDIR: /tmp/.ccache-temp
  CCACHE_COMPRESS: 1
  CASHER_TIME_OUT: 599 # one second less than 10m to avoid 10m timeout error: https://github.com/Project-OSRM/osrm-backend/issues/2742
  CCACHE_VERSION: 3.3.1
  CMAKE_VERSION: 3.21.2
  ENABLE_NODE_BINDINGS: "ON"

jobs:
  windows:
   # needs: format-taginfo-docs
    runs-on: windows-2022
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - run: pip install conan==1.50.0
    - run: conan --version
    - run: cmake --version
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: node --version
    - run: npm --version
    - run: npm install --ignore-scripts
    - run: npm link --ignore-scripts
    - uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: |
        .\scripts\ci\windows-build.bat

  # format-taginfo-docs:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: 12
  #   - name: Enable Node.js cache
  #     uses: actions/cache@v2
  #     with:
  #       path: ~/.npm
  #       key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
  #       restore-keys: |
  #         ${{ runner.os }}-node-
  #   - name: Prepare environment
  #     run: |
  #       npm ci --ignore-scripts
  #       export MASON=${GITHUB_WORKSPACE}/scripts/mason.sh
  #       ${MASON} install clang-format 10.0.0
  #       echo "$(${MASON} prefix clang-format 10.0.0)/bin" >> $GITHUB_PATH
  #   - name: Run checks
  #     run: |
  #       ./scripts/check_taginfo.py taginfo.json profiles/car.lua
  #       ./scripts/format.sh && ./scripts/error_on_dirty.sh
  #       node ./scripts/validate_changelog.js
  #       npm run docs && ./scripts/error_on_dirty.sh
  